name: build and test
on:
  push:
    branches:
    - master

jobs:

  buildandtest:
    name: Build and Test on Go ${{matrix.go}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18', '1.17']
    steps:
    - name: Set up Go ${{matrix.go}}
      uses: actions/setup-go@v3
      with:
        go-version: ${{matrix.go}}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Test Go packages as root
      run: go test -v -p 1 -exec sudo ./...
      
    - name: Test Go packages as ordinary user
      run: go test -v -p 1 ./...
